# Generated by Django 4.2.7 on 2026-04-14 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(blank=True, default='Unknown', max_length=300)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('num_reviews', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('genre', models.CharField(blank=True, default='', max_length=200)),
                ('price', models.CharField(blank=True, default='', max_length=50)),
                ('availability', models.CharField(blank=True, default='', max_length=100)),
                ('book_url', models.URLField(max_length=255, unique=True)),
                ('cover_image_url', models.URLField(blank=True, default='', max_length=500)),
                ('ai_summary', models.TextField(blank=True, default='')),
                ('ai_genre', models.CharField(blank=True, default='', max_length=200)),
                ('ai_sentiment', models.CharField(blank=True, default='', max_length=100)),
                ('ai_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QAHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('sources', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField()),
                ('content', models.TextField()),
                ('chroma_id', models.CharField(max_length=200, unique=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='books.book')),
            ],
            options={
                'ordering': ['chunk_index'],
            },
        ),
    ]
